services:
  - type: web
    name: planejamento-financeiro
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: APP_USERNAME
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: PLUGGY_CLIENT_ID
        sync: false
      - key: PLUGGY_CLIENT_SECRET
        sync: false
